# Path to the DSSP executable
dssp_exec: "/usr/local/dssp-3.0.10/bin/mkdssp"

# pLDDT score cutoff
plddt_cutoff: 70

# UniProt IDs of the proteins of interest
uniprot_ids:


  # CALR 
  P27797:
    dir_name: "calr"

